### ISSUE TITLE
EvalArgs in ...tasks/abx_phoneme/task.py 

### ISSUE THREAD

**Issue by hallapmark** [zerospeech/benchmarks#10] opened 2022-12-19 15:29 UTC
https://github.com/zerospeech/benchmarks/blob/72c0950f219c65750ed5b4f2a72d48440ef49fc3/zerospeech/benchmarks/tasks/abx_phoneme/task.py#L54-L72
1) Instead of `mode=` for this eval `speaker_mode=` and `context_mode=` are needed.
2) We are using a seed now. `seed=` (`EvalArgs` already accepts this). We need to save the seed in the results .csv.

P.S. Technically, you do not _have_ to pass in a seed here if you plan on using the default value in eval_ABX. But in that case you would need to retrieve the used seed from the return value. That is possible in the proposed new return value format, see pull request at https://github.com/zerospeech/libri-light-abx2/pull/4

**Comment by nhamilakis** [comment] 2023-01-02 17:23
I have corrected the arguments to include context & seed.

I have a question on the passing of the .item file
Should i pass all three item files each time (`dev-clean.item`, `phoneme-dev-clean.item`,  `triphone-dev-clean.item`) or should i call the eval function once with each item file ?

**Comment by hallapmark** [comment] 2023-01-02 18:24
> I have corrected the arguments to include context & seed.
> 
> I have a question on the passing of the .item file Should i pass all three item files each time (`dev-clean.item`, `phoneme-dev-clean.item`, `triphone-dev-clean.item`) or should i call the eval function once with each item file ?

There's a few things:

1.  To directly answer the question, once with each item file. `path_item_file` in the args above takes a single item file path. So if you want to run _phoneme abx_ on dev-clean, that would be one call with the `phoneme-dev-clean` item file, and if you want to run the triphone condition, that would be a new call with the `triphone-dev-clean` item file. 

2.  However, unless I am mistaken, I think we should have only two, not three, item files for a given subset: `phoneme-dev-clean.item` and `triphone-dev-clean.item`. _triphone-dev-clean_ is exactly the same file as _dev-clean_ used to be in libri-light-abx1, but since we now have two sets of item files, just the description _triphone_ is added to the filename to help differentiate them (alternatively, you could drop 'triphone' and keep the old file name, then you would have `dev-clean.item` and `phoneme-dev-clean.item`).

3. There is one difference in the call to ABX2 **depending on the item file**. `phoneme-dev-clean.item` should be run `speaker_mode=all` and `context_mode=all`. Whereas `triphone-dev-clean.item` should be run `speaker_mode=all` and `context_mode=within`. This is because context_mode `any` does not make sense with the triphone item file. 

4. Running the triphone item file with the `context_mode=within` condition essentially gives you the `libri-light-abx1` score. The only difference is that in `libri-light-abx1` it was not possible to input the seed, so the result will be slightly different on account of the seed. So perhaps it is more advantageous to run only the new one from now on, I am not sure how you want to organize it in terms of datasets and benchmarks ...

**Comment by nhamilakis** [comment] 2023-01-03 09:05
Oh okay, so if i understood correctly, it could correspond to something like the following code :

```python
if ContextMode.within in context.as_set():
    abx_sets.append('dev-clean', dataset.index.subsets.dev_clean.get('phoneme_item_file', npy_file_list)

 if ContextMode.any in context.as_set():
    abx_sets.append('dev-clean', dataset.index.subsets.dev_clean.get('triphone_item_file', npy_file_list)


for label, item_file, file_list in abx_sets:
   res = zrc_abx2.EvalABX().eval_abx(....)
   ...
```
And if the context is set to `all` the `context.as_set()` will contain both `within` and `any` which means the user will run both.
If the user wants to run only one of them then he can set the context to either `within` either `any` and it will only run one of them.

**Comment by hallapmark** [comment] 2023-01-03 16:51
The discussion here overlaps with the discussion in issue #12. I think the answer to this https://github.com/zerospeech/benchmarks/issues/10#issuecomment-1369528580 is in https://github.com/zerospeech/benchmarks/issues/12#issuecomment-1369946158

Maybe it is possible to switch on something like 
`ABXEvalType` which has the options
- triphone
- phoneme_within
- phoneme_any
- all

and then `ContextMode` would remain the same as currently and it would signify the context types that the abx2 module understands (i.e. 'all', 'within', 'any'). So correspoindingly a specific evaluation would be defined along the following lines
```python 
if eval_type == ABXEvalType.triphone:
    eval_def == EvalDef(ContextMode.within,  ...  get('triphone_item_file'))
elif eval_type == ABXEvalType.phoneme_within:
    eval_def ==  EvalDef(ContextMode.within,  ... get('phoneme_item_file'))
elif eval_type == ABXEvalType.phoneme_any:
    eval_def == EvalDef(ContextMode.any, ... get('phoneme_item_file'))
elif eval_type == ABXEvalType.all:
    eval_defs.append(EvalDef(ContextMode.within,  ...  get('triphone_item_file')))
    eval_defs.append(EvalDef(ContextMode.all, ...  get('phonemne_item_file')))
```

**Comment by nhamilakis** [comment] 2023-01-04 11:20
Yes, this comment was done before i opened the #12 issue. I think i understand better the different options now, so I created a new branch [12-clean-up-abx-ls](https://github.com/zerospeech/benchmarks/tree/12-clean-up-abx-ls), and i'm working on removing the old abxLS benchmark and keeping only the abxLSPhon. 

I added this enumeration : 
```python
class ContextMode(str, Enum):
    """ ABX context mode of computation """
    all = "all"
    phoneme_any = "phoneme-any"
    phoneme_within = "phoneme-within"
    triphone_within = 'triphone-within'
   ```

To allow specification of item-file and context.
And the filtered out output at the end will look something like this : 

```json
{
        "subset": "dev-clean",
        "granularity": "triphone",
        "speaker_mode": "across",
        "context_mode": "within",
        "score": 0.49813100695610046,
        "item_file": "triphone-dev-clean.item",
        "pooling": "none",
        "seed": 3459
}
```

**Comment by nhamilakis** [comment] 2023-01-04 11:21
Duplicate of #12

**Closed by nhamilakis** 2023-01-04 11:21 UTC
Labels: enhancement, question
